// Every fixture, read twice: once by this addon and once by OVITO, compared field by
// field. OVITO is the reference implementation for these formats, so a disagreement is
// a bug here until proven otherwise.
//
// The ground truth lives in oracle.json, generated by `npm run oracle` under an OVITO
// interpreter and committed — so these tests run in CI, which has no OVITO. Regenerate
// only when a fixture changes, and read the diff: a moved reference is a real claim.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const { scanFrames, readFrame, readHeader } = require('..');

const FIXTURES = path.join(__dirname, 'fixtures');
const oracle = JSON.parse(fs.readFileSync(path.join(__dirname, 'oracle.json'), 'utf8'));

/** float32 storage here against OVITO's float64; 1e-4 is far tighter than either loses. */
const TOLERANCE = 1e-4;

/**
 * OVITO renames the per-atom columns it recognizes to its own display names. Where the
 * quantity is the same and only the label differs, the comparison needs the mapping.
 */
const OVITO_PROPERTY_ALIASES = {
    'Molecule Identifier': 'mol',
    Charge: 'q',
    // Extended-XYZ column names OVITO promotes to its standard properties. This addon
    // keeps the name the file used, which is what a caller sees in a column list.
    'Potential Energy': 'local_energy',
    'Kinetic Energy': 'kinetic_energy',
    'Total Energy': 'total_energy',
    Coordination: 'n_neighb',
    Cluster: 'cluster',
    Radius: 'radius'
};

/**
 * Columns OVITO surfaces that this addon deliberately does not, with the reason. Listed
 * rather than ignored wholesale, so a new divergence cannot hide in the gap.
 *
 * The two data models differ in one respect worth stating: OVITO folds recognized
 * column triples into vector properties (vx/vy/vz become a single `Velocity`), and
 * derives scalars from them. This addon reports every column separately under the name
 * the file used. Neither is wrong, but it means a vector-valued OVITO property has no
 * single column here to compare against.
 */
const NOT_COMPARED = {
    // OVITO expands a data file's Masses section into a per-particle Mass column. This
    // addon returns the per-type table instead (massesByType), which is the same
    // information without one float per atom; asserted separately below.
    Mass: 'returned as massesByType instead of per particle',
    // Derived by OVITO from its Velocity vector: |v|, not any single column in the file.
    'Velocity Magnitude': 'a magnitude OVITO derives, not a column the file carries',
    // Data-file columns beyond id/type/position are not extracted: unlike a dump, a data
    // file has no column header naming them, so there is nothing to key them by.
    Charge: 'data files carry no column names to key extra columns by',
    'Molecule Identifier': 'data files carry no column names to key extra columns by'
};

const closeTo = (actual, expected, what) => {
    assert.ok(
        Math.abs(actual - expected) <= TOLERANCE,
        `${what}: ${actual} is not within ${TOLERANCE} of ${expected}`
    );
};

/** The cell vectors and origin a box description implies, in OVITO's column order. */
const cellFromBox = (box) => ({
    a: [box.xhi - box.xlo, 0, 0],
    b: [box.xy, box.yhi - box.ylo, 0],
    c: [box.xz, box.yz, box.zhi - box.zlo],
    origin: [box.xlo, box.ylo, box.zlo]
});

const isDataFile = (name) => name.endsWith('.data');

for (const [name, expected] of Object.entries(oracle.fixtures)) {
    const file = path.join(FIXTURES, name);

    test(`${name}: frame count matches OVITO`, () => {
        assert.equal(scanFrames(file).frames.length, expected.frameCount);
    });

    expected.frames.forEach((reference, index) => {
        test(`${name}: frame ${index} matches OVITO`, () => {
            const frame = readFrame(file, {
                frame: index,
                includeIds: true,
                properties: ['*']
            });

            assert.equal(frame.metadata.natoms, reference.natoms, 'atom count');
            assert.equal(frame.positions.length, reference.natoms * 3, 'position buffer length');

            reference.positions.forEach((position, atom) => {
                position.forEach((value, axis) => {
                    closeTo(frame.positions[atom * 3 + axis], value, `atom ${atom} axis ${axis}`);
                });
            });

            assert.deepEqual(Array.from(frame.types), reference.types, 'types');
            if (reference.ids) {
                assert.deepEqual(Array.from(frame.ids), reference.ids, 'ids');
            }

            if (reference.cell) {
                // OVITO's cell is 3 rows x 4 columns: a column per vector, then the origin.
                reference.cell.forEach((row, axis) => {
                    frame.metadata.cellVectors.forEach((vector, index) => {
                        closeTo(vector[axis], row[index], `cell vector ${index}, axis ${axis}`);
                    });
                    closeTo(frame.metadata.cellOrigin[axis], row[3], `cell origin axis ${axis}`);
                });

                // boxBounds has to agree with the vectors it was derived from.
                const derived = cellFromBox(frame.metadata.boxBounds);
                ['a', 'b', 'c'].forEach((label, index) => {
                    derived[label].forEach((value, axis) => {
                        closeTo(value, frame.metadata.cellVectors[index][axis], `boxBounds ${label}[${axis}]`);
                    });
                });

                assert.deepEqual(frame.metadata.pbc, reference.pbc, 'periodic boundary flags');
            } else {
                // The file declares no cell, so OVITO reports none. This addon reports the
                // extent of the atoms instead, which is derived rather than read — there is
                // nothing in the file to check it against, only that it is not periodic.
                assert.deepEqual(frame.metadata.pbc, [false, false, false],
                    'a file with no declared cell is not periodic');
            }

            for (const [ovitoName, values] of Object.entries(reference.properties)) {
                if (NOT_COMPARED[ovitoName]) continue;

                const ours = OVITO_PROPERTY_ALIASES[ovitoName] ?? ovitoName;
                const column = frame.properties?.[ours];
                assert.ok(column, `expected column ${ours} (OVITO's "${ovitoName}") to be present`);
                values.forEach((value, atom) => {
                    closeTo(column[atom], value, `${ours}[${atom}]`);
                });
            }
        });
    });

    if (isDataFile(name)) {
        test(`${name}: per-type masses cover what OVITO reports per particle`, () => {
            const frame = readFrame(file, { includeIds: true });
            const reference = expected.frames[0];
            const perParticleMass = reference.properties.Mass;

            if (!perParticleMass) return;

            // Same information, one entry per type instead of one per atom.
            assert.ok(frame.massesByType, 'massesByType');
            reference.types.forEach((type, atom) => {
                closeTo(frame.massesByType[type - 1], perParticleMass[atom], `mass of atom ${atom}`);
            });
        });
    }

    test(`${name}: readHeader agrees with readFrame about the same frame`, () => {
        // The cheap path and the full path must not be able to disagree — the cheap one
        // is what decides whether a file is accepted at all.
        const header = readHeader(file);
        const frame = readFrame(file);

        assert.equal(header.format, frame.metadata.format);
        assert.equal(header.timestep, frame.metadata.timestep);
        assert.equal(header.natoms, frame.metadata.natoms);
        assert.deepEqual(header.pbc, frame.metadata.pbc);
        assert.deepEqual(header.headers, frame.metadata.headers);

        if (expected.frames[0].cell) {
            assert.deepEqual(header.boxBounds, frame.metadata.boxBounds);
            assert.deepEqual(header.cellVectors, frame.metadata.cellVectors);
        } else {
            // The one documented divergence between the two paths: with no declared cell
            // there is nothing to report until the atoms have been read, so the header
            // leaves it empty and the frame fills in their extent.
            assert.deepEqual(header.cellVectors, [[0, 0, 0], [0, 0, 0], [0, 0, 0]]);
        }
    });
}

test('the oracle covers every fixture on disk', () => {
    // A fixture with no ground truth would otherwise sit there looking tested.
    const onDisk = fs.readdirSync(FIXTURES).filter((name) => !name.startsWith('.')).sort();
    assert.deepEqual(onDisk, Object.keys(oracle.fixtures).sort());
});
